# Generated by Django 5.0.6 on 2026-05-18 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AmoCRMToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField()),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AmoCRM Token',
                'verbose_name_plural': 'AmoCRM Tokenlar',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amocrm_id', models.IntegerField(db_index=True, unique=True)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('first_name', models.CharField(blank=True, default='', max_length=255)),
                ('last_name', models.CharField(blank=True, default='', max_length=255)),
                ('company', models.CharField(blank=True, default='', max_length=255)),
                ('phone', models.CharField(blank=True, default='', max_length=100)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('responsible_user_id', models.IntegerField(blank=True, null=True)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Kontakt',
                'verbose_name_plural': 'Kontaktlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amocrm_id', models.IntegerField(db_index=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('sort', models.IntegerField(default=0)),
                ('is_main', models.BooleanField(default=False)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pipeline',
                'verbose_name_plural': 'Pipelinelar',
                'ordering': ['sort'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amocrm_id', models.IntegerField(db_index=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('role', models.CharField(blank=True, default='', max_length=100)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'AmoCRM Foydalanuvchi',
                'verbose_name_plural': 'AmoCRM Foydalanuvchilar',
            },
        ),
        migrations.CreateModel(
            name='PipelineStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amocrm_id', models.IntegerField(db_index=True)),
                ('name', models.CharField(max_length=255)),
                ('sort', models.IntegerField(default=0)),
                ('color', models.CharField(blank=True, default='', max_length=50)),
                ('is_editable', models.BooleanField(default=True)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='amocrm.pipeline')),
            ],
            options={
                'verbose_name': 'Pipeline Status',
                'verbose_name_plural': 'Pipeline Statuslar',
                'ordering': ['sort'],
                'unique_together': {('amocrm_id', 'pipeline')},
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amocrm_id', models.IntegerField(db_index=True, unique=True)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('status_id', models.IntegerField(blank=True, null=True)),
                ('pipeline_id', models.IntegerField(blank=True, null=True)),
                ('responsible_user_id', models.IntegerField(blank=True, null=True)),
                ('loss_reason', models.CharField(blank=True, default='', max_length=500)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('contacts', models.ManyToManyField(blank=True, related_name='leads', to='amocrm.contact')),
                ('pipeline_ref', models.ForeignKey(blank=True, db_column='pipeline_ref_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='amocrm.pipeline')),
                ('status_ref', models.ForeignKey(blank=True, db_column='status_ref_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='amocrm.pipelinestatus')),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leadlar',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status_id', 'pipeline_id'], name='amocrm_lead_status__8da353_idx'), models.Index(fields=['responsible_user_id'], name='amocrm_lead_respons_6f2ceb_idx'), models.Index(fields=['created_at'], name='amocrm_lead_created_58c813_idx')],
            },
        ),
    ]
