# Generated by Django 5.0.6 on 2026-05-19 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amocrm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='source',
            field=models.CharField(choices=[('amocrm', 'AmoCRM'), ('bitrix', 'Bitrix24')], db_index=True, default='amocrm', max_length=20),
        ),
        migrations.AddField(
            model_name='lead',
            name='source',
            field=models.CharField(choices=[('amocrm', 'AmoCRM'), ('bitrix', 'Bitrix24')], db_index=True, default='amocrm', max_length=20),
        ),
    ]
