# Generated by Django 5.0.6 on 2026-05-22 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('file', models.FileField(upload_to='rag_docs/', verbose_name='Fayl')),
                ('file_type', models.CharField(max_length=10, verbose_name='Fayl turi')),
                ('chunk_count', models.IntegerField(default=0, verbose_name="Bo'laklar soni")),
                ('status', models.CharField(choices=[('processing', 'Qayta ishlanmoqda'), ('ready', 'Tayyor'), ('error', 'Xatolik')], default='processing', max_length=20, verbose_name='Holat')),
                ('error', models.TextField(blank=True, default='', verbose_name='Xatolik matni')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Yuklangan vaqt')),
            ],
            options={
                'verbose_name': 'Bilim hujjati',
                'verbose_name_plural': 'Bilim hujjatlari',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager_id', models.IntegerField(db_index=True, default=0, verbose_name='Menejer ID')),
                ('role', models.CharField(choices=[('human', 'Foydalanuvchi'), ('ai', 'AI')], max_length=10, verbose_name='Rol')),
                ('content', models.TextField(verbose_name='Matn')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vaqt')),
            ],
            options={
                'verbose_name': 'Suhbat xabari',
                'verbose_name_plural': 'Suhbat xabarlari',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['manager_id', 'created_at'], name='ai_analyst__manager_8ade34_idx')],
            },
        ),
    ]
