# Generated by Django 5.0.6 on 2026-06-03 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_analyst', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('daily', 'Kunlik'), ('weekly', 'Haftalik')], db_index=True, max_length=10, verbose_name='Tur')),
                ('source', models.CharField(blank=True, default='', max_length=20, verbose_name='Manba')),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('content', models.TextField(verbose_name='Matn (Markdown)')),
                ('metrics', models.JSONField(blank=True, default=dict, verbose_name="Ko'rsatkichlar")),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Vaqt')),
            ],
            options={
                'verbose_name': 'AI hisobot',
                'verbose_name_plural': 'AI hisobotlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MetricAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.CharField(max_length=50, verbose_name="Ko'rsatkich")),
                ('source', models.CharField(blank=True, default='', max_length=20, verbose_name='Manba')),
                ('severity', models.CharField(choices=[('info', "Ma'lumot"), ('warning', 'Ogohlantirish'), ('critical', 'Jiddiy')], default='warning', max_length=10, verbose_name='Darajasi')),
                ('message', models.CharField(max_length=500, verbose_name='Xabar')),
                ('value', models.FloatField(blank=True, null=True, verbose_name='Qiymat')),
                ('threshold', models.FloatField(blank=True, null=True, verbose_name='Chegara')),
                ('is_read', models.BooleanField(db_index=True, default=False, verbose_name="O'qilgan")),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Vaqt')),
            ],
            options={
                'verbose_name': 'Metrik alert',
                'verbose_name_plural': 'Metrik alertlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='feedback',
            field=models.CharField(blank=True, choices=[('', '—'), ('up', 'Foydali'), ('down', 'Foydasiz')], default='', max_length=4, verbose_name='Baho'),
        ),
    ]
