# Generated by Django 5.0.6 on 2026-05-18 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True)),
                ('total_leads', models.IntegerField(default=0)),
                ('new_leads', models.IntegerField(default=0)),
                ('closed_won', models.IntegerField(default=0)),
                ('closed_lost', models.IntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('avg_deal_size', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('conversion_rate', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Kunlik Statistika',
                'verbose_name_plural': 'Kunlik Statistikalar',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('week_end', models.DateField()),
                ('report_text', models.TextField()),
                ('stats_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Haftalik Hisobot',
                'verbose_name_plural': 'Haftalik Hisobotlar',
                'ordering': ['-week_start'],
            },
        ),
        migrations.CreateModel(
            name='ManagerStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('manager_id', models.IntegerField()),
                ('manager_name', models.CharField(max_length=255)),
                ('leads_count', models.IntegerField(default=0)),
                ('won_count', models.IntegerField(default=0)),
                ('lost_count', models.IntegerField(default=0)),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('conversion_rate', models.FloatField(default=0)),
            ],
            options={
                'verbose_name': 'Menejer Statistikasi',
                'verbose_name_plural': 'Menejer Statistikalari',
                'ordering': ['-date', '-revenue'],
                'unique_together': {('date', 'manager_id')},
            },
        ),
    ]
